# The Purpose of this workflow file is to enable us to automatically 
# Synchronize the staging repository with the upstream repository
# of CATcher-org/CATcher. 

name: Fetch Upstream Master to Staging

on:
  push:
    branches: [ master ]

jobs:
  fetch_from_upstream:
    if: ${{ github.repository == 'CATcher-org/CATcher' }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps: 
      - name: Checkout Upstream 
        uses: actions/checkout@v2
        with:
          repository: CATcher-org/CATcher-staging
          ref: master 
          token: ${{ secrets.STAGING_TOKEN }}
          fetch-depth: 0 
      - name: Merge Upstream 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/CATcher-org/CATcher.git 
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories
          git push origin master -f
